### ISSUE TITLE
Encountering Size Mismatch Error in Updated Code

### ISSUE THREAD

**Issue by anonymousA123** [kyegomez/BitNet#45]
While running the updated code, I encountered an issue as follows:
![1](https://github.com/kyegomez/BitNet/assets/103629060/2a5f1cb9-3d8c-471a-bd7c-04eb0df6ba8b)

I would greatly appreciate any guidance or assistance you can provide to help resolve this issue.

**Comment by AnonymousA12345** [comment]
Thank you so much for your reply. May I ask if you have encountered the following error message??  Because when I add squeeze to self.gamma and self.beta, it reports an error:
![1](https://github.com/kyegomez/BitNet/assets/134117681/03b05729-54a1-4c74-89fe-493ca4f09815)
Additionally, does training with the latest version of the code still generate gibberish messages like in issue #23?

**Comment by Yuan0320** [comment]
Encountered the same problem
